import fs from "fs";
import { FilePrompts } from "./buildPromptsFromRules";
import { promptFilePathToTargetFilePath } from "./promptFilePathToTargetFilePath";

export const removeGeneratedFilePrompts = (
  prompts: FilePrompts
): FilePrompts => {
  // check if the file to be generated by the prompt already exists
  const remaingingFiles = Object.keys(prompts).filter(
    (path) => !fs.existsSync(promptFilePathToTargetFilePath(path))
  );
  // remove the generated files
  const remainingPrompts: FilePrompts = {};
  remaingingFiles.forEach((path) => {
    remainingPrompts[path] = prompts[path];
  });
  return remainingPrompts;
};
